### ISSUE TITLE
duplicate key in table '#sql-3292_16'

### ISSUE THREAD

**Issue by Bekcpear** [FriendsOfFlarum/byobu#46]
hi, i got an issue when i'm installing flarum via web interface with flagrow/byobu installed.

```
SQLSTATE[23000]: Integrity constraint violation: 1022 Can't write; duplicate key in table '#sql-3292_16' (SQL: alter table `fxxrecipients` add constraint recipients_discussion_id_foreign foreign key (`discussion_id`) references `fxxdiscussions` (`id`) on delete cascade)
```

**ENV**

* Docker 17.06.1-ce
* CentOS 7
* PHP 7.1.8
* Mysql 5.7.19-community
* Nginx 1.12.1
* flarum/core version: v0.1.0-beta.7
* flagrow/byobu version: 0.1.0-beta.21

**How to reproduce**

1. install the latest flarum/core with the latest flagrow/byobu
2. use MariaDB-10.1.26 or Mysql-5.7.19 as database, ans use PHP-7.1.6/7/8
3. install flarum via web interface.

**Comment by Ralkage** [comment]
Hi @Bekcpear, sorry we could not help you troubleshoot this issue in time.

If you still have an active Flarum install with this same issue, please feel free to comment here or open a new issue. This issue is aged and breaking changes happened when Flarum Beta 8 was released and this extension was updated.

With that being said, we will proceed with the closure of this issue.
