### ISSUE TITLE
Leave a discussion?

### ISSUE THREAD

**Issue by jordanjay29** [FriendsOfFlarum/byobu#5]
Especially a discussion with multiple recipients, how would a participant leave? 

Could they retain a copy of the messages thus far? 

And could they be added back in? 

Is it better to make this simple (move your feet, lose your seat; aka when you leave it's all gone) or complex to preserve ownership of messages?

**Comment by Luceos** [comment]
Very good question, food for thought.

**Comment by Luceos** [comment]
I'd like to suggest a "leave this discussion" with the following challenges:

- user was part of a group, we can't remove the group

**Comment by jordanjay29** [comment]
I'm wondering whether the Ignore function of the Subs extension already implements this feature to satisfaction.

**Comment by Luceos** [comment]
I might have a solution for this. The recipients table holds information when a recipient was removed (`removed_at`). If I would prioritise the state of a removed user of his access from a group state, he should not be able to participate anymore. That's the backend side of the solution, the frontend side is way more complex because the interface supports adding recipients, not blocking them.. A solution for that would be to add another autocomplete recipient search based on whether the recipient autocomplete has any groups.

Thoughts?

**Comment by Luceos** [comment]
In case of blacklisting a user (groups doesn't make too much sense). We could create another column on the table called blacklisted_at, a button on the PD that says "Blacklist recipient" and re-use the recipient modal to select a user to blacklist.

**Comment by Luceos** [comment]
Given the scenario that a user leaves a discussion voluntarily, we set a column value `left_at`. 

- This will remove the discussion for that user without giving any feedback to the other participants of the PD in case the user was part of any of the groups set as recipient. 

- In addition to allowing someone to leave a private discussion, how are we going to undo that when that user cannot see the private discussion anymore?

**Comment by Cu8eeeR** [comment]
@luceos any progress? Last feature which is needed to make this extension perfect ;)

**Comment by pflstr** [comment]
In my opinion, there are several questions to be answered.

a) Who can add or remove recipients of a private conversation? If it's only the admin it's quite easy, we just need to add a special case for a recipient wanting to leave a private discussion. This right will be given in addition to the right of the admin.

b) If the right to add and remove recipients of a private conversation is given to non-staff usergroups as well, one should be aware, that a breach of confidence might result, if posts older than the time of the change of recipients become accessible to new recipients. This needs to be avoided to protect a forum owner from legal implications. The right to leave such a discussion voluntarily would apply in this case as well.

c) If users are allowed to leave and reenter a private discussion, we may need more than one entry date and / or more than one leave date. The database query to filter out the posts that should be shown to such a user may become quite complex. What should be done with quotes from posts, that are not supposed to be shown to a certain user?

My suggestion: Don't let the list of recipients be altered after the start of a private discussion: The only exception should the case of a user leaving such a discussion voluntarily. Even in this case one should favor a solution, where the given recipient is not removed from the list but instead the discussion can be ignored by any recipient (and the ignoring can be revoked without legal consequences, because the user never really left).

If participants of a private discussion want to expell a certain user, they can simply start a new discussion without the given user.

One last question remains:

d) Who should have the right to close a private discussion? The original poster? Any participant? And who should have the right to reopen a closed discussion?

**Comment by luceos** [comment]
@pflstr you have questions, I understand. But these are unrelated to this issue, feel free to open a new issue? I'll be deleting your reply once you did. I sadly can't do this for you.

@Cu8eeeR as soon as we get to it. I'm sorry I can't give you any indication yet.
